### ISSUE TITLE
Possible issue with selector '#.identifier'

### ISSUE THREAD

**Issue by tmpfs** [fb55/css-what#18]
When an `id` selector contains a period I get a runtime error here:

https://github.com/fb55/css-what/blob/master/index.js#L97

Such as (truncated for brevity):

```
TypeError: Cannot read property '0' of null
    at getName (/home/muji/git/makestatic/compiler/packages/auto-title/node_modules/css-what/index.js:97:36)
    at parseSelector (/home/muji/git/makestatic/compiler/packages/auto-title/node_modules/css-what/index.js:145:13)
    at parse (/home/muji/git/makestatic/compiler/packages/auto-title/node_modules/css-what/index.js:82:13)
    at Function.compileUnsafe (/home/muji/git/makestatic/compiler/packages/auto-title/node_modules/css-select/lib/compile.js:33:15)
    at Function.select [as selectOne] (/home/muji/git/makestatic/compiler/packages/auto-title/node_modules/css-select/index.js:20:51)
...
```

As browsers handle this fine I am wondering whether it is legal to have a period in an `id` as far as selectors go.

Can you advise? If you feel it's worth patching I am happy to give it a shot and submit a PR.

**Comment by fb55** [comment]
This is definitely a bug, for now escaping the period should fix this.

**Comment by airmite** [comment]
Hello, 

This bug is it fix ? Because i found a similar problem i think. 

Thank you

**Comment by fb55** [comment]
This wasn’t fixed. Feel free to take a stab at it!
